#!/usr/bin/env python3
"""Run a local signal-deck briefing pipeline into an auditable run folder.

The script is intentionally standard-library only. It validates the ingestion
packet, generates a final briefing, syncs the visual composition contract to the
generated briefing identity, writes a compact Telegram-ready message, and can
optionally build the Vite renderer against the generated artifacts.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from generate_briefing import transform_packet
from validate_briefing import validate_briefing
from validate_signal_input import expect_dict, validate_input_packet
from validate_visual_composition import validate_visual_composition

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data" / "signal-input.sample.json"
DEFAULT_COMPOSITION = ROOT / "data" / "visual-composition.sample.json"
DEFAULT_RUNS_DIR = ROOT / "runs"
WEB_ROOT = ROOT / "apps" / "web"


class PipelineError(RuntimeError):
    """Raised when the local briefing pipeline cannot complete."""


def load_json(path: Path, label: str) -> dict[str, Any]:
    if not path.exists():
        raise PipelineError(f"{label} not found: {path}")
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise PipelineError(f"Invalid JSON in {label} ({path}): {exc}") from exc
    if not isinstance(data, dict):
        raise PipelineError(f"{label} must be a JSON object: {path}")
    return data


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n")


def derive_run_date(packet: dict[str, Any], explicit_date: str | None) -> str:
    if explicit_date:
        return explicit_date
    created_at = str(packet.get("meta", {}).get("createdAt", ""))
    if "T" in created_at:
        return created_at.split("T", 1)[0]
    return datetime.now(UTC).date().isoformat()


def sync_composition_to_briefing(composition: dict[str, Any], briefing: dict[str, Any]) -> dict[str, Any]:
    meta = briefing["meta"]
    composition = json.loads(json.dumps(composition))
    composition.setdefault("meta", {})
    composition["meta"]["compositionId"] = f"{meta['briefingId']}-composition"
    composition["meta"]["createdAt"] = meta.get("publishedAt", datetime.now(UTC).isoformat())
    composition["meta"]["language"] = meta.get("language", composition["meta"].get("language", "en"))
    if meta.get("topics"):
        composition["meta"]["tags"] = meta["topics"]

    composition["sourceBriefing"] = {
        "briefingId": meta["briefingId"],
        "editionDate": meta["editionDate"],
        "slug": meta["slug"],
        "topics": meta.get("topics", []),
    }
    return composition


def build_telegram_message(briefing: dict[str, Any]) -> str:
    meta = briefing["meta"]
    hero = briefing["hero"]
    top_line = briefing["topLine"]
    radar_items = briefing["radar"]["items"][:3]
    watch_items = briefing["watchlist"]["items"][:2]
    spanish = str(meta.get("language", "")).lower().startswith("es")

    lines = [
        f"# signal-deck — {meta['editionDate']}",
        "",
        f"**{top_line['title']}**",
        "",
        hero.get("thesis") or top_line["body"],
        "",
        "## Señales para leer primero" if spanish else "## Signals to read first",
    ]
    for item in radar_items:
        lines.append(f"- **{item['label']}**: {item['text']}")

    if "readerTranslation" in briefing:
        lines.extend(["", "## Traducción para el lector" if spanish else "## Reader translation"])
        for item in briefing["readerTranslation"]["items"][:3]:
            lines.append(f"- **{item['role']}**: {item['body']}")

    lines.extend(["", "## Qué vigilar ahora" if spanish else "## Watch next"])
    for item in watch_items:
        lines.append(f"- {item['text']}")

    footer = "Generado por el pipeline determinístico local de signal-deck." if spanish else "Generated by the local deterministic signal-deck pipeline."
    lines.extend(["", footer])
    return "\n".join(lines)


def append_public_link(message: str, public_url: str | None) -> str:
    if not public_url:
        return message
    normalized_url = public_url.rstrip("/") + "/"
    spanish = "Generado por el pipeline determinístico" in message
    label = "Lee el briefing completo" if spanish else "Read the full briefing"
    return f"{message.rstrip()}\n\n{label}: {normalized_url}"


def renderer_relative(path: Path) -> str:
    return os.path.relpath(path, WEB_ROOT)


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def run_renderer_build(briefing_path: Path, composition_path: Path) -> None:
    env = os.environ.copy()
    env["SIGNAL_DECK_BRIEFING_PATH"] = renderer_relative(briefing_path)
    env["SIGNAL_DECK_COMPOSITION_PATH"] = renderer_relative(composition_path)
    subprocess.run(["npm", "run", "build"], cwd=WEB_ROOT, env=env, check=True)


def run_pipeline(args: argparse.Namespace) -> dict[str, Any]:
    input_path = args.input.resolve()
    composition_template_path = args.composition_template.resolve()
    runs_dir = args.runs_dir.resolve()

    packet = expect_dict(load_json(input_path, "signal input"), "signal-input")
    validate_input_packet(packet)

    run_date = derive_run_date(packet, args.run_date)
    run_dir = runs_dir / run_date
    input_snapshot_path = run_dir / "signal-input.json"
    briefing_path = run_dir / "briefing.final.json"
    composition_path = run_dir / "visual-composition.json"
    telegram_path = run_dir / "telegram-message.md"
    manifest_path = run_dir / "manifest.json"

    briefing = transform_packet(packet)
    validate_briefing(briefing)

    composition_template = load_json(composition_template_path, "visual composition template")
    composition = sync_composition_to_briefing(composition_template, briefing)
    validate_visual_composition(composition)

    write_json(input_snapshot_path, packet)
    write_json(briefing_path, briefing)
    write_json(composition_path, composition)
    telegram_message = append_public_link(build_telegram_message(briefing), args.public_url)
    write_text(telegram_path, telegram_message)

    build_status = "not-requested"
    if args.build_renderer:
        run_renderer_build(briefing_path, composition_path)
        build_status = "passed"

    manifest = {
        "status": "ok",
        "runDate": run_date,
        "input": display_path(input_snapshot_path),
        "briefing": display_path(briefing_path),
        "visualComposition": display_path(composition_path),
        "telegramMessage": display_path(telegram_path),
        "rendererBuild": build_status,
    }
    write_json(manifest_path, manifest)
    return manifest


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the local signal-deck briefing pipeline.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Input packet JSON path.")
    parser.add_argument(
        "--composition-template",
        type=Path,
        default=DEFAULT_COMPOSITION,
        help="Visual composition template JSON path.",
    )
    parser.add_argument("--runs-dir", type=Path, default=DEFAULT_RUNS_DIR, help="Directory for run artifacts.")
    parser.add_argument("--run-date", help="Run date folder to use, YYYY-MM-DD. Defaults to input meta.createdAt date.")
    parser.add_argument("--public-url", help="Public briefing URL to include in the Telegram-ready message.")
    parser.add_argument("--build-renderer", action="store_true", help="Build the Vite renderer against generated artifacts.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv or sys.argv[1:])
    try:
        manifest = run_pipeline(args)
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"ERROR: renderer build failed with exit code {exc.returncode}") from exc
    except PipelineError as exc:
        raise SystemExit(f"ERROR: {exc}") from exc

    print("OK: local briefing pipeline completed")
    for key, value in manifest.items():
        print(f"{key}: {value}")


if __name__ == "__main__":
    main()
